language: bash

sudo: false
addons:
  apt:
    packages:
    - debhelper
    - dpkg-dev

script:
- dpkg-buildpackage -us -uc

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/13627e9a6e8fa0dec084 # m-doc/general
    on_success: change
    on_failure: always
    on_start: never
