language: bash

sudo: false
addons:
  apt:
    packages:
    - debhelper
    - dpkg-dev

script:
- sh update-version.sh
- dpkg-buildpackage -us -uc

deploy:
  provider: bintray
  file: deploy.json
  user:
    secure: JS7AAw8QqfMGQdDxfMXopnOVaFBNubh1P2vKeoOLbdx/VNxRu5A6u3VQn3/t4P1bbMeyc57nurMM/SnKbnWwMMVa9kBUASyPBZeua51fcWPhniW0uZciRRQEkcta095ijf4IG0WHIVrt/ilScNU6qyX6YEgtVTVPg367CqOVl5RwegZ5UZhV5Uu7A9tBPPHFS/QsGlfXHtjzhC/E7ue7ELkJo249HuE9WjwvUqKeuWy5wzNxY0weAPYKaSrVLUStX2AXfqfn33WFRGwaa8qZz0lIvwt5kYBGQJd0/XeX1Gc32tcvidrggnU7OHZHOUUwV9Jqb5SAifnVHRg/gsk3aynPlEn8nY+IhVccvoKLsrg6deT5+iTjt40p2icnYziL/C8QZlLviiSLfFlqywtqkZZN9JOWVd3kOaor7vY5vNy15gTZ7iNfEwPufKElxul5Bi8wvyhJksSq0jrRU15ZsuUevssjrC7kNmcSzoYWgtSakA8m9kxtV6YeDm2zfOTOym4gDpZiOVcN4541DcSEr/jHlc6bKCdsN0Pl8tg0oP8dG9fmVmD0lnW8fJpyEo1lGw8nItrwFv4Kp3zO7y+2O3EKbn/ypGcN+jzdMIHZ8hTM2eOFpnvWB4hsmKnFeElvK16eobJcEeQzui4ZrRsRcwUvafmgmxeOTJfRorlOy+A=
  key:
    secure: fEUXqoUKhNnS8Kfj/z+LEGXm4rlLdRxeUbjnzHJyTnMiYgBDLO0+0aBvJzGPByXCCTNSrnObMy59yWbAgHsh5k9jLFz8AzspdHS+Vd7UYjlTSIykm10lMFa0WT32SHSgpaIEYXOBLCUVSjSc6EynndHMS2CfCYEiPLqRROij2otSr/aQRUZ6s01kaYJL19UXe3TLkh/pk4qIyksHddALvWuAFpgme5kuXW7mZHZzgB7pGvXUxZVBfVt9v51TmsyVLNNdF4krMpG/8CQP688BjH7n5buaiORrR1PheS/hfYDtVtMg3lAoro6K8IMz3iSdBJIWOpCcpX+oawVamosDqpeIzcF0a+QT395uwUfdCVEbNeLHydQzDXL6Cg0a+1s/EIe1E5LaW2oMY/xGWAK6Y6KANo8HuNQd7mWg7sEThDyaH6Gdamfcl3r4TL0uNEi6SxYvTDdEfQbtiPRhsJzOwRlNEF3IoFbz8CKaWELnalXBU9PK+wNQAGHXG5YXpWBuDfx57TFK0TmSEeCzP7iZ2A7Gjo9bAxiwBGE3VUMBds3ZxjGNc8ksRZOn2P9gCQ/a1B3ZRYB8BIXFqG1nEZCLN6fU5lT0x6HiqFv5mr84b07ZmVVisAdkcK/wCpRFnEAtVvz13DtBaHXJzmcXuPk9hLRcfuGMebMJL8HRlz8fjyM=

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/13627e9a6e8fa0dec084 # m-doc/general
    on_success: change
    on_failure: always
    on_start: never
