#!/bin/sh

set -e

if [ "$#" -eq 0 ]; then
    "E: no source part spefified"
    exit 1
fi

ARGS=""
if [ "$#" -gt 1 ]; then
    ARGS=$(echo "$@" | cut -d' ' -f-$(expr "$#" - 1))
fi

SOURCE=$(echo "$@" | cut -d' ' -f"$#")
case "$SOURCE" in -*)
    ARGS="$ARGS $SOURCE"
    SOURCE=""
esac

apt-get \
  -o Dir::Etc::SourceList="sources.list.d/${SOURCE}.list" \
  -o Dir::Etc::SourceParts="-" \
  -o APT::Get::List-Cleanup="0" \
  $ARGS update
